[project]
name = "mcp-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anyio>=4.12.1",
    "httpx>=0.28.1",
    "mcp>=1.26.0",
    "starlette>=0.52.1",
    "uvicorn>=0.41.0",
]
